### PR TITLE
Add support for Unified Interface 

### PR DESCRIPTION
**Pull request by mehmetseckin**
:clipboard: **Description**

Adds support for Unified Interface.

:white_check_mark: **Code Review Checklist**

- [x] I completed a complete self-review of my contribution.

I tested the extension for the following browsers:
  - [x] Google Chrome
  - [x] Mozilla Firefox
  - [x] Microsoft Edge
  - [x] Microsoft Edge (Chromium)

I tested the extension on the following versions of the product:
 - [x] Dynamics 365 v9
 - [x] Dynamics 365 v8.2
 - [ ] Dynamics CRM 2016
 - [ ] Dynamics CRM 2015
 - [ ] Dynamics CRM 2013

### CODE REVIEW

**Comment by haffinn** [comment]
@mehmetseckin @onurmenal 
Any news on this PR ? Very much looking forward to it!

**Comment by mehmetseckin** [comment]
@haffinn we're waiting on a review from @onurmenal, hopefully we can get it published after that.

In the meantime, we may be able to build and release an alpha version from the UCI branch, so watch out for a release.

**Comment by haffinn** [comment]
@mehmetseckin Great thanks for the info, I'll watch out for the alpha version

**Comment by mehmetseckin** [comment]
@haffinn I've gone ahead and created an [alpha release][1] from the UCI branch as suggested. 

You will need to download and install as an unpacked extension, please follow the guidance available for your browser(s) of choice:

- [Chrome][2]
- [Firefox][3]
- [Edge (EdgeHTML)][5]
- [Edge (Chromium)][4]

> Please bear in mind this is still work in progress, there are incomplete and/or broken actions, so any feedback/improvements on this PR or new PRs are welcome.

Hope this helps! 😃 

[1]: https://github.com/onurmenal/crm-power-pane/releases/tag/1.1.0.52
[2]: https://developer.chrome.com/extensions/getstarted#manifest
[3]: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#Installing
[4]: https://docs.microsoft.com/en-gb/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension#run-your-extension-locally-in-your-browser-while-developing-it-side-loading
[5]: https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/adding-and-removing-extensions

**Comment by haffinn** [comment]
@mehmetseckin thank you! I will try this out

**Pull request merged**
